version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis